"""
Radical Transparency Layer.
Assembles recommendation traces that explain WHY a recommendation was made.
Every trace is deterministic — built from Data Layer outputs, not generated by LLM.
"""

from dataclasses import dataclass

from supabase import Client

from app.db.queries import get_citations_for_rule, get_food_by_id


@dataclass
class DataSource:
    food: str
    source: str
    source_id: str
    source_url: str | None
    verified_date: str | None


@dataclass
class Evidence:
    claim: str
    citation: str
    display_text: str


@dataclass
class RecommendationTrace:
    logic_chain: list[str]
    data_source: DataSource | None
    evidence: Evidence | None
    recommendation_type: str  # "rule_based" or "ai_generated"


async def build_recommendation_trace(
    db: Client,
    food_id: str | None,
    food_name: str,
    gap_info: dict,
    rule_key: str | None,
    health_conditions: list[str],
    recommendation_type: str = "ai_generated",
) -> RecommendationTrace:
    """Build a transparency trace for a recommendation.

    The trace explains the full logic chain:
    1. What food group gap was detected
    2. What health context is relevant
    3. What food was suggested and why
    4. Where the nutrition data comes from
    5. What published evidence supports the rule
    """
    # Build logic chain
    logic_chain = []

    # Step 1: Food group gap
    if gap_info:
        fg_name = gap_info.get("food_group_name", gap_info.get("food_group_slug", ""))
        days = gap_info.get("days_present", 0)
        total = gap_info.get("target_days", 7)
        logic_chain.append(
            f"You've had {fg_name} foods {days} out of the past {total} days"
        )

    # Step 2: Health context
    if health_conditions:
        condition_names = {
            "iron_deficiency_anemia": "iron-deficiency anemia",
            "pcos": "PCOS",
            "hypothyroidism": "hypothyroidism",
            "pregnancy_t1": "first trimester pregnancy",
            "pregnancy_t2": "second trimester pregnancy",
            "pregnancy_t3": "third trimester pregnancy",
            "perimenopause": "perimenopause",
            "type2_diabetes": "type 2 diabetes",
            "celiac": "celiac disease",
            "vegetarian": "vegetarian diet",
            "vegan": "vegan diet",
        }
        for condition in health_conditions:
            name = condition_names.get(condition, condition)
            logic_chain.append(f"Your health profile notes {name}")

    # Step 3: Why this food
    if food_name:
        logic_chain.append(f"{food_name} was suggested to help fill this gap")

    # Get data source from food DB
    data_source = None
    if food_id:
        food_data = await get_food_by_id(db, food_id)
        if food_data:
            data_source = DataSource(
                food=food_data["name"],
                source=food_data.get("source", "Unknown"),
                source_id=food_data.get("source_id", ""),
                source_url=food_data.get("source_url"),
                verified_date=food_data.get("verified_date"),
            )

    # Get evidence citation
    evidence = None
    if rule_key:
        citations = await get_citations_for_rule(db, rule_key)
        if citations:
            c = citations[0]
            evidence = Evidence(
                claim=c["claim"],
                citation=c["citation_text"],
                display_text=c["display_text"],
            )

    return RecommendationTrace(
        logic_chain=logic_chain,
        data_source=data_source,
        evidence=evidence,
        recommendation_type=recommendation_type,
    )
