"""
Curated composite dishes across 4 cuisine regions.
Nutrient estimates calculated from ingredient profiles using
standard recipe calculation methodology (yield + retention factors).
Each dish includes transparency metadata.
"""

WEST_AFRICAN_DISHES = [
    {
        "name": "Jollof Rice",
        "aliases": ["jollof", "west african rice"],
        "tags": ["west_african", "tomato_based", "spiced"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:WA001",
        "food_groups": ["whole_grains", "orange_red_vegetables", "herbs_spices", "alliums"],
        "nutrients": {"protein": 4.5, "iron": 1.2, "calcium": 18.0, "fiber": 1.5, "vitamin_c": 8.0, "folate": 20.0, "zinc": 0.8, "magnesium": 22.0, "vitamin_a": 120.0},
    },
    {
        "name": "Egusi Soup",
        "aliases": ["melon seed soup"],
        "tags": ["west_african", "iron_rich", "high_protein", "leafy_green"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA + FAO/INFOODS Africa",
        "source_id": "NURSH:WA002",
        "food_groups": ["nuts_seeds", "dark_leafy_greens", "iron_rich_proteins", "herbs_spices"],
        "nutrients": {"protein": 8.0, "iron": 3.5, "calcium": 80.0, "fiber": 3.0, "vitamin_c": 15.0, "folate": 45.0, "zinc": 1.5, "magnesium": 40.0, "vitamin_a": 300.0},
    },
    {
        "name": "Fufu (pounded yam)",
        "aliases": ["foufou", "foutou", "pounded yam"],
        "tags": ["vegetarian", "west_african", "gluten_free"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:WA003",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 1.5, "iron": 0.5, "calcium": 10.0, "fiber": 1.8, "vitamin_c": 8.0, "folate": 12.0, "zinc": 0.3, "magnesium": 15.0},
    },
    {
        "name": "Groundnut Soup",
        "aliases": ["peanut soup", "nkate nkwan"],
        "tags": ["west_african", "high_protein", "iron_rich"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:WA004",
        "food_groups": ["nuts_seeds", "iron_rich_proteins", "herbs_spices", "alliums"],
        "nutrients": {"protein": 10.0, "iron": 2.0, "calcium": 30.0, "fiber": 2.5, "vitamin_c": 5.0, "folate": 35.0, "zinc": 1.8, "magnesium": 50.0},
    },
    {
        "name": "Pepper Soup",
        "aliases": ["point and kill", "spicy broth"],
        "tags": ["west_african", "anti_inflammatory", "spiced"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:WA005",
        "food_groups": ["iron_rich_proteins", "herbs_spices", "alliums"],
        "nutrients": {"protein": 12.0, "iron": 1.8, "calcium": 15.0, "fiber": 0.8, "vitamin_c": 10.0, "folate": 15.0, "zinc": 2.0, "magnesium": 20.0},
    },
    {
        "name": "Moin Moin",
        "aliases": ["moi moi", "steamed bean pudding"],
        "tags": ["vegetarian", "west_african", "high_protein", "iron_rich"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:WA006",
        "food_groups": ["legumes_pulses", "alliums", "orange_red_vegetables"],
        "nutrients": {"protein": 7.0, "iron": 2.5, "calcium": 35.0, "fiber": 4.0, "vitamin_c": 6.0, "folate": 100.0, "zinc": 1.2, "magnesium": 40.0},
    },
    {
        "name": "Suya (grilled meat skewers)",
        "aliases": ["suya", "tsire"],
        "tags": ["non_vegetarian", "west_african", "high_protein", "spiced"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:WA007",
        "food_groups": ["iron_rich_proteins", "nuts_seeds", "herbs_spices"],
        "nutrients": {"protein": 22.0, "iron": 2.5, "calcium": 20.0, "fiber": 1.0, "vitamin_c": 0.5, "folate": 10.0, "zinc": 4.0, "magnesium": 30.0},
    },
    {
        "name": "Fried Plantain (Dodo)",
        "aliases": ["dodo", "platano frito", "kelewele"],
        "tags": ["vegetarian", "west_african", "caribbean", "vitamin_a_rich"],
        "cuisine_region": "west_african",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:WA008",
        "food_groups": ["orange_red_vegetables"],
        "nutrients": {"protein": 1.0, "iron": 0.5, "calcium": 3.0, "fiber": 1.5, "vitamin_c": 5.0, "folate": 15.0, "zinc": 0.1, "magnesium": 28.0, "vitamin_a": 400.0},
    },
]

EAST_ASIAN_DISHES = [
    {
        "name": "Congee (rice porridge)",
        "aliases": ["jook", "okayu", "zhou"],
        "tags": ["east_asian", "chinese", "gentle_stomach"],
        "cuisine_region": "east_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA001",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 1.5, "iron": 0.2, "calcium": 5.0, "fiber": 0.3, "vitamin_c": 0.0, "folate": 3.0, "zinc": 0.3, "magnesium": 8.0},
    },
    {
        "name": "Miso Soup",
        "aliases": ["misoshiru"],
        "tags": ["vegetarian", "east_asian", "japanese", "fermented", "probiotic"],
        "cuisine_region": "east_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA002",
        "food_groups": ["fermented_foods", "legumes_pulses", "alliums"],
        "nutrients": {"protein": 3.5, "iron": 0.8, "calcium": 20.0, "fiber": 1.2, "vitamin_c": 0.5, "folate": 10.0, "zinc": 0.5, "magnesium": 15.0},
    },
    {
        "name": "Bibimbap",
        "aliases": ["korean mixed rice"],
        "tags": ["east_asian", "korean", "balanced"],
        "cuisine_region": "east_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA003",
        "food_groups": ["whole_grains", "dark_leafy_greens", "iron_rich_proteins", "fermented_foods", "orange_red_vegetables"],
        "nutrients": {"protein": 10.0, "iron": 2.5, "calcium": 50.0, "fiber": 3.0, "vitamin_c": 10.0, "folate": 40.0, "zinc": 1.5, "magnesium": 30.0},
    },
    {
        "name": "Pho (beef)",
        "aliases": ["pho bo", "vietnamese noodle soup"],
        "tags": ["east_asian", "vietnamese", "iron_rich"],
        "cuisine_region": "east_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA004",
        "food_groups": ["whole_grains", "iron_rich_proteins", "herbs_spices", "alliums"],
        "nutrients": {"protein": 12.0, "iron": 2.0, "calcium": 15.0, "fiber": 1.0, "vitamin_c": 5.0, "folate": 15.0, "zinc": 2.5, "magnesium": 20.0},
    },
    {
        "name": "Mapo Tofu",
        "aliases": ["spicy tofu", "mabo doufu"],
        "tags": ["east_asian", "chinese", "high_protein", "spiced"],
        "cuisine_region": "east_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA005",
        "food_groups": ["legumes_pulses", "calcium_sources", "herbs_spices", "alliums"],
        "nutrients": {"protein": 9.0, "iron": 3.0, "calcium": 180.0, "fiber": 1.5, "vitamin_c": 3.0, "folate": 20.0, "zinc": 1.0, "magnesium": 35.0},
    },
    {
        "name": "Sushi Roll (salmon)",
        "aliases": ["maki", "salmon roll"],
        "tags": ["east_asian", "japanese", "omega_3_rich"],
        "cuisine_region": "east_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA006",
        "food_groups": ["whole_grains", "omega3_sources", "fermented_foods"],
        "nutrients": {"protein": 8.0, "iron": 0.5, "calcium": 12.0, "fiber": 0.5, "vitamin_c": 1.0, "folate": 10.0, "zinc": 0.5, "magnesium": 18.0, "omega_3_dha": 0.5, "omega_3_epa": 0.2},
    },
    {
        "name": "Japchae (glass noodles)",
        "aliases": ["korean glass noodles", "chapchae"],
        "tags": ["east_asian", "korean", "balanced"],
        "cuisine_region": "east_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA007",
        "food_groups": ["whole_grains", "dark_leafy_greens", "iron_rich_proteins", "alliums"],
        "nutrients": {"protein": 6.0, "iron": 1.5, "calcium": 25.0, "fiber": 2.0, "vitamin_c": 8.0, "folate": 30.0, "zinc": 1.0, "magnesium": 20.0},
    },
    {
        "name": "Tom Yum Soup",
        "aliases": ["tom yam", "thai hot sour soup"],
        "tags": ["east_asian", "thai", "anti_inflammatory"],
        "cuisine_region": "southeast_asian",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:EA008",
        "food_groups": ["iron_rich_proteins", "herbs_spices", "alliums"],
        "nutrients": {"protein": 8.0, "iron": 0.8, "calcium": 15.0, "fiber": 0.5, "vitamin_c": 12.0, "folate": 10.0, "zinc": 0.8, "magnesium": 20.0},
    },
]

LATIN_AMERICAN_DISHES = [
    {
        "name": "Black Bean Soup",
        "aliases": ["sopa de frijoles negros"],
        "tags": ["vegetarian", "latin_american", "cuban", "high_fiber", "iron_rich"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA001",
        "food_groups": ["legumes_pulses", "alliums", "herbs_spices"],
        "nutrients": {"protein": 7.0, "iron": 2.5, "calcium": 30.0, "fiber": 8.0, "vitamin_c": 5.0, "folate": 120.0, "zinc": 1.0, "magnesium": 50.0},
    },
    {
        "name": "Arroz con Pollo",
        "aliases": ["chicken and rice", "rice with chicken"],
        "tags": ["latin_american", "balanced"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA002",
        "food_groups": ["whole_grains", "iron_rich_proteins", "herbs_spices", "alliums", "orange_red_vegetables"],
        "nutrients": {"protein": 12.0, "iron": 1.5, "calcium": 20.0, "fiber": 1.5, "vitamin_c": 10.0, "folate": 15.0, "zinc": 1.5, "magnesium": 22.0},
    },
    {
        "name": "Pupusas",
        "aliases": ["salvadoran stuffed tortilla"],
        "tags": ["latin_american", "salvadoran", "calcium_rich"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA003",
        "food_groups": ["whole_grains", "legumes_pulses", "calcium_sources"],
        "nutrients": {"protein": 6.5, "iron": 1.2, "calcium": 85.0, "fiber": 3.0, "vitamin_c": 2.0, "folate": 25.0, "zinc": 0.8, "magnesium": 22.0},
    },
    {
        "name": "Ceviche",
        "aliases": ["seviche", "cebiche"],
        "tags": ["latin_american", "peruvian", "omega_3_rich", "high_protein"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA004",
        "food_groups": ["omega3_sources", "iron_rich_proteins", "citrus_berries", "alliums"],
        "nutrients": {"protein": 15.0, "iron": 0.5, "calcium": 15.0, "fiber": 0.5, "vitamin_c": 30.0, "folate": 10.0, "zinc": 0.5, "magnesium": 25.0},
    },
    {
        "name": "Gallo Pinto",
        "aliases": ["rice and beans", "costa rican beans and rice"],
        "tags": ["vegetarian", "latin_american", "costa_rican", "high_fiber"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA005",
        "food_groups": ["whole_grains", "legumes_pulses", "alliums"],
        "nutrients": {"protein": 6.0, "iron": 1.8, "calcium": 25.0, "fiber": 5.0, "vitamin_c": 3.0, "folate": 80.0, "zinc": 0.9, "magnesium": 35.0},
    },
    {
        "name": "Pozole",
        "aliases": ["posole", "hominy soup"],
        "tags": ["latin_american", "mexican", "iron_rich"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA006",
        "food_groups": ["whole_grains", "iron_rich_proteins", "herbs_spices", "alliums"],
        "nutrients": {"protein": 10.0, "iron": 1.5, "calcium": 20.0, "fiber": 3.0, "vitamin_c": 8.0, "folate": 15.0, "zinc": 2.0, "magnesium": 25.0},
    },
    {
        "name": "Arepas",
        "aliases": ["venezuelan corn cake", "colombian arepa"],
        "tags": ["vegetarian", "latin_american", "venezuelan", "colombian", "gluten_free"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA007",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 3.0, "iron": 0.5, "calcium": 5.0, "fiber": 2.0, "vitamin_c": 0.0, "folate": 10.0, "zinc": 0.4, "magnesium": 15.0},
    },
    {
        "name": "Guacamole",
        "aliases": ["avocado dip"],
        "tags": ["vegetarian", "vegan", "latin_american", "mexican", "healthy_fat"],
        "cuisine_region": "latin_american",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:LA008",
        "food_groups": ["nuts_seeds", "citrus_berries", "alliums", "herbs_spices"],
        "nutrients": {"protein": 2.0, "iron": 0.5, "calcium": 15.0, "fiber": 5.0, "vitamin_c": 12.0, "folate": 60.0, "zinc": 0.5, "magnesium": 25.0},
    },
]

MIDDLE_EASTERN_DISHES = [
    {
        "name": "Hummus",
        "aliases": ["houmous", "chickpea dip"],
        "tags": ["vegetarian", "vegan", "middle_eastern", "high_protein", "high_fiber"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME001",
        "food_groups": ["legumes_pulses", "nuts_seeds", "herbs_spices"],
        "nutrients": {"protein": 7.9, "iron": 2.44, "calcium": 38.0, "fiber": 6.0, "vitamin_c": 5.0, "folate": 83.0, "zinc": 1.83, "magnesium": 71.0},
    },
    {
        "name": "Falafel",
        "aliases": ["ta'amia"],
        "tags": ["vegetarian", "vegan", "middle_eastern", "high_protein"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME002",
        "food_groups": ["legumes_pulses", "herbs_spices", "alliums"],
        "nutrients": {"protein": 6.5, "iron": 2.0, "calcium": 35.0, "fiber": 4.0, "vitamin_c": 3.0, "folate": 70.0, "zinc": 1.2, "magnesium": 40.0},
    },
    {
        "name": "Tabbouleh",
        "aliases": ["tabbouli", "tabouli"],
        "tags": ["vegetarian", "vegan", "middle_eastern", "lebanese", "vitamin_c_rich"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME003",
        "food_groups": ["whole_grains", "herbs_spices", "citrus_berries"],
        "nutrients": {"protein": 2.5, "iron": 1.5, "calcium": 20.0, "fiber": 3.0, "vitamin_c": 25.0, "folate": 40.0, "zinc": 0.5, "magnesium": 20.0},
    },
    {
        "name": "Shakshuka",
        "aliases": ["eggs in tomato sauce"],
        "tags": ["vegetarian", "middle_eastern", "north_african", "iron_rich"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME004",
        "food_groups": ["iron_rich_proteins", "orange_red_vegetables", "herbs_spices", "alliums"],
        "nutrients": {"protein": 7.5, "iron": 1.8, "calcium": 40.0, "fiber": 2.0, "vitamin_c": 15.0, "folate": 35.0, "zinc": 1.0, "magnesium": 15.0},
    },
    {
        "name": "Ful Medames",
        "aliases": ["foul", "fava bean stew"],
        "tags": ["vegetarian", "vegan", "middle_eastern", "egyptian", "high_protein", "iron_rich"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME005",
        "food_groups": ["legumes_pulses", "herbs_spices", "citrus_berries", "alliums"],
        "nutrients": {"protein": 8.0, "iron": 1.8, "calcium": 40.0, "fiber": 5.5, "vitamin_c": 10.0, "folate": 90.0, "zinc": 1.0, "magnesium": 45.0},
    },
    {
        "name": "Fattoush",
        "aliases": ["lebanese bread salad"],
        "tags": ["vegetarian", "middle_eastern", "lebanese", "vitamin_c_rich"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME006",
        "food_groups": ["whole_grains", "citrus_berries", "herbs_spices"],
        "nutrients": {"protein": 2.0, "iron": 0.8, "calcium": 15.0, "fiber": 2.5, "vitamin_c": 18.0, "folate": 25.0, "zinc": 0.3, "magnesium": 12.0},
    },
    {
        "name": "Baba Ganoush",
        "aliases": ["baba ghanouj", "eggplant dip"],
        "tags": ["vegetarian", "vegan", "middle_eastern", "lebanese"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME007",
        "food_groups": ["nuts_seeds", "herbs_spices", "citrus_berries"],
        "nutrients": {"protein": 2.5, "iron": 0.6, "calcium": 25.0, "fiber": 3.0, "vitamin_c": 5.0, "folate": 20.0, "zinc": 0.5, "magnesium": 15.0},
    },
    {
        "name": "Lamb Kofta",
        "aliases": ["kofte", "kafta"],
        "tags": ["non_vegetarian", "middle_eastern", "high_protein", "iron_rich"],
        "cuisine_region": "middle_eastern",
        "source": "Recipe calculation from USDA ingredients",
        "source_id": "NURSH:ME008",
        "food_groups": ["iron_rich_proteins", "herbs_spices", "alliums"],
        "nutrients": {"protein": 18.0, "iron": 2.5, "calcium": 20.0, "fiber": 0.5, "vitamin_c": 2.0, "folate": 12.0, "zinc": 3.5, "magnesium": 22.0, "b12": 2.0},
    },
]
