"""
Curated South Asian food seed data.
Sources: Indian Nutrient Databank (INDB), ICMR-NIN Indian Food Composition Tables (IFCT 2024).
Each entry includes transparency metadata (source, source_id, verified_date).
"""

INDIAN_FOODS = [
    # === South Indian ===
    {
        "name": "Idli",
        "aliases": ["idly", "steamed rice cake"],
        "tags": ["vegetarian", "south_indian", "fermented", "steamed"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A001",
        "food_groups": ["fermented_foods", "whole_grains"],
        "nutrients": {
            "protein": 3.9, "iron": 0.7, "calcium": 11.0, "fiber": 0.8,
            "vitamin_c": 0.0, "folate": 8.0, "zinc": 0.5, "magnesium": 16.0,
        },
    },
    {
        "name": "Dosa",
        "aliases": ["dosai", "crispy crepe", "masala dosa"],
        "tags": ["vegetarian", "south_indian", "fermented"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A002",
        "food_groups": ["fermented_foods", "whole_grains"],
        "nutrients": {
            "protein": 3.1, "iron": 1.1, "calcium": 30.0, "fiber": 0.5,
            "vitamin_c": 0.0, "folate": 10.0, "zinc": 0.4, "magnesium": 14.0,
        },
    },
    {
        "name": "Sambar",
        "aliases": ["sambhar", "lentil vegetable stew"],
        "tags": ["vegetarian", "south_indian", "iron_rich", "high_fiber"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A003",
        "food_groups": ["legumes_pulses", "herbs_spices"],
        "nutrients": {
            "protein": 3.2, "iron": 1.5, "calcium": 25.0, "fiber": 2.1,
            "vitamin_c": 5.0, "folate": 30.0, "zinc": 0.6, "magnesium": 20.0,
        },
    },
    {
        "name": "Coconut Chutney",
        "aliases": ["nariyal chutney", "thengai chutney"],
        "tags": ["vegetarian", "south_indian", "condiment"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A004",
        "food_groups": ["nuts_seeds", "herbs_spices"],
        "nutrients": {
            "protein": 1.5, "iron": 0.8, "calcium": 6.0, "fiber": 3.0,
            "vitamin_c": 1.0, "folate": 5.0, "zinc": 0.3, "magnesium": 18.0,
        },
    },
    {
        "name": "Rasam",
        "aliases": ["pepper water", "chaaru"],
        "tags": ["vegetarian", "south_indian", "anti_inflammatory"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A005",
        "food_groups": ["herbs_spices", "legumes_pulses"],
        "nutrients": {
            "protein": 1.0, "iron": 0.5, "calcium": 10.0, "fiber": 0.5,
            "vitamin_c": 8.0, "folate": 12.0, "zinc": 0.2, "magnesium": 8.0,
        },
    },
    {
        "name": "Uttapam",
        "aliases": ["uthappam", "thick pancake"],
        "tags": ["vegetarian", "south_indian", "fermented"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A006",
        "food_groups": ["fermented_foods", "whole_grains"],
        "nutrients": {
            "protein": 4.0, "iron": 1.0, "calcium": 15.0, "fiber": 1.2,
            "vitamin_c": 2.0, "folate": 10.0, "zinc": 0.5, "magnesium": 15.0,
        },
    },
    # === North Indian ===
    {
        "name": "Dal (Yellow Lentil)",
        "aliases": ["dal", "daal", "yellow dal", "toor dal", "arhar dal"],
        "tags": ["vegetarian", "north_indian", "iron_rich", "high_protein", "high_fiber"],
        "cuisine_region": "north_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:B001",
        "food_groups": ["legumes_pulses"],
        "nutrients": {
            "protein": 7.0, "iron": 2.5, "calcium": 20.0, "fiber": 3.5,
            "vitamin_c": 0.5, "folate": 60.0, "zinc": 1.0, "magnesium": 30.0,
        },
    },
    {
        "name": "Dal Makhani",
        "aliases": ["maa ki dal", "black lentil dal"],
        "tags": ["vegetarian", "north_indian", "iron_rich", "high_protein"],
        "cuisine_region": "north_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:B002",
        "food_groups": ["legumes_pulses", "calcium_sources"],
        "nutrients": {
            "protein": 5.5, "iron": 2.8, "calcium": 40.0, "fiber": 3.0,
            "vitamin_c": 0.5, "folate": 45.0, "zinc": 0.9, "magnesium": 28.0,
        },
    },
    {
        "name": "Roti",
        "aliases": ["chapati", "phulka", "flatbread"],
        "tags": ["vegetarian", "north_indian", "whole_grain"],
        "cuisine_region": "north_indian",
        "source": "ICMR-NIN IFCT 2024",
        "source_id": "IFCT:W001",
        "food_groups": ["whole_grains"],
        "nutrients": {
            "protein": 3.5, "iron": 1.5, "calcium": 12.0, "fiber": 1.8,
            "vitamin_c": 0.0, "folate": 15.0, "zinc": 0.6, "magnesium": 22.0,
        },
    },
    {
        "name": "Palak Paneer",
        "aliases": ["spinach paneer", "saag paneer"],
        "tags": ["vegetarian", "north_indian", "iron_rich", "calcium_rich"],
        "cuisine_region": "north_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:B003",
        "food_groups": ["dark_leafy_greens", "calcium_sources"],
        "nutrients": {
            "protein": 6.0, "iron": 3.0, "calcium": 150.0, "fiber": 1.5,
            "vitamin_c": 10.0, "folate": 50.0, "zinc": 0.8, "magnesium": 35.0,
        },
    },
    {
        "name": "Raita",
        "aliases": ["yogurt salad", "cucumber raita"],
        "tags": ["vegetarian", "north_indian", "fermented", "calcium_rich"],
        "cuisine_region": "north_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:B004",
        "food_groups": ["fermented_foods", "calcium_sources"],
        "nutrients": {
            "protein": 2.5, "iron": 0.2, "calcium": 80.0, "fiber": 0.3,
            "vitamin_c": 2.0, "folate": 8.0, "zinc": 0.4, "magnesium": 10.0,
        },
    },
    {
        "name": "Basmati Rice",
        "aliases": ["white rice", "chawal"],
        "tags": ["vegetarian", "indian", "grain"],
        "cuisine_region": "indian",
        "source": "ICMR-NIN IFCT 2024",
        "source_id": "IFCT:G001",
        "food_groups": ["whole_grains"],
        "nutrients": {
            "protein": 2.7, "iron": 0.2, "calcium": 10.0, "fiber": 0.4,
            "vitamin_c": 0.0, "folate": 8.0, "zinc": 0.5, "magnesium": 12.0,
        },
    },
    {
        "name": "Chicken Curry",
        "aliases": ["chicken masala", "murgh curry"],
        "tags": ["non_vegetarian", "indian", "iron_rich", "high_protein"],
        "cuisine_region": "indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:C001",
        "food_groups": ["iron_rich_proteins", "herbs_spices"],
        "nutrients": {
            "protein": 12.0, "iron": 1.5, "calcium": 15.0, "fiber": 0.5,
            "vitamin_c": 3.0, "folate": 10.0, "zinc": 1.8, "magnesium": 20.0,
        },
    },
    {
        "name": "Biryani",
        "aliases": ["chicken biryani", "mutton biryani", "veg biryani"],
        "tags": ["indian", "rice_dish", "spiced"],
        "cuisine_region": "indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:C002",
        "food_groups": ["whole_grains", "herbs_spices", "iron_rich_proteins"],
        "nutrients": {
            "protein": 8.0, "iron": 1.2, "calcium": 20.0, "fiber": 0.8,
            "vitamin_c": 2.0, "folate": 15.0, "zinc": 1.2, "magnesium": 18.0,
        },
    },
    {
        "name": "Chole (Chickpea Curry)",
        "aliases": ["chana masala", "chole masala", "chickpea curry"],
        "tags": ["vegetarian", "north_indian", "iron_rich", "high_protein", "high_fiber"],
        "cuisine_region": "north_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:B005",
        "food_groups": ["legumes_pulses", "herbs_spices"],
        "nutrients": {
            "protein": 6.3, "iron": 2.1, "calcium": 45.0, "fiber": 5.0,
            "vitamin_c": 3.0, "folate": 55.0, "zinc": 1.1, "magnesium": 32.0,
        },
    },
    {
        "name": "Mango Lassi",
        "aliases": ["lassi", "yogurt drink"],
        "tags": ["vegetarian", "indian", "fermented", "calcium_rich"],
        "cuisine_region": "indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:D001",
        "food_groups": ["fermented_foods", "calcium_sources", "citrus_berries"],
        "nutrients": {
            "protein": 3.0, "iron": 0.2, "calcium": 100.0, "fiber": 0.5,
            "vitamin_c": 15.0, "folate": 10.0, "zinc": 0.3, "magnesium": 12.0,
        },
    },
    {
        "name": "Aloo Gobi",
        "aliases": ["potato cauliflower", "gobi aloo"],
        "tags": ["vegetarian", "north_indian"],
        "cuisine_region": "north_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:B006",
        "food_groups": ["cruciferous", "herbs_spices"],
        "nutrients": {
            "protein": 2.5, "iron": 0.8, "calcium": 18.0, "fiber": 2.0,
            "vitamin_c": 20.0, "folate": 25.0, "zinc": 0.3, "magnesium": 15.0,
        },
    },
    {
        "name": "Pongal",
        "aliases": ["ven pongal", "khara pongal"],
        "tags": ["vegetarian", "south_indian", "whole_grain"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A007",
        "food_groups": ["whole_grains", "legumes_pulses"],
        "nutrients": {
            "protein": 4.5, "iron": 1.0, "calcium": 15.0, "fiber": 1.5,
            "vitamin_c": 0.5, "folate": 20.0, "zinc": 0.6, "magnesium": 18.0,
        },
    },
    {
        "name": "Upma",
        "aliases": ["uppuma", "semolina porridge"],
        "tags": ["vegetarian", "south_indian", "whole_grain"],
        "cuisine_region": "south_indian",
        "source": "Indian Nutrient Databank (INDB)",
        "source_id": "INDB:A008",
        "food_groups": ["whole_grains"],
        "nutrients": {
            "protein": 3.5, "iron": 0.8, "calcium": 12.0, "fiber": 1.0,
            "vitamin_c": 1.0, "folate": 12.0, "zinc": 0.4, "magnesium": 14.0,
        },
    },
]
