"""
International raw ingredients from USDA FoodData Central.
These are base ingredients used across multiple cuisines.
Nutrient values per 100g from USDA SR Legacy / Foundation Foods.
"""

INTERNATIONAL_INGREDIENTS = [
    # ============================================================
    # GRAINS & STARCHES (used across all cuisines)
    # ============================================================
    {
        "name": "Millet (cooked)",
        "aliases": ["bajra", "pearl millet", "finger millet", "ragi"],
        "tags": ["vegetarian", "gluten_free", "whole_grain", "african", "indian"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169702",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 3.51, "iron": 0.63, "calcium": 3.0, "fiber": 1.3, "vitamin_c": 0.0, "folate": 19.0, "zinc": 0.91, "magnesium": 44.0},
    },
    {
        "name": "Teff (cooked)",
        "aliases": ["tef", "injera grain"],
        "tags": ["vegetarian", "gluten_free", "whole_grain", "east_african", "iron_rich"],
        "cuisine_region": "east_african",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169747",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 3.87, "iron": 2.05, "calcium": 49.0, "fiber": 2.8, "vitamin_c": 0.0, "folate": 0.0, "zinc": 1.11, "magnesium": 50.0},
    },
    {
        "name": "Sorghum (cooked)",
        "aliases": ["jowar", "milo", "guinea corn"],
        "tags": ["vegetarian", "gluten_free", "whole_grain", "african", "indian"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169716",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 8.37, "iron": 3.36, "calcium": 13.0, "fiber": 6.7, "vitamin_c": 0.0, "folate": 0.0, "zinc": 1.67, "magnesium": 0.0},
    },
    {
        "name": "Cassava (raw)",
        "aliases": ["yuca", "manioc", "tapioca root"],
        "tags": ["vegetarian", "gluten_free", "west_african", "latin_american"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169988",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 1.36, "iron": 0.27, "calcium": 16.0, "fiber": 1.8, "vitamin_c": 20.6, "folate": 27.0, "zinc": 0.34, "magnesium": 21.0},
    },
    {
        "name": "Plantain (cooked)",
        "aliases": ["platano", "cooking banana", "dodo"],
        "tags": ["vegetarian", "gluten_free", "west_african", "latin_american", "caribbean"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169247",
        "food_groups": ["orange_red_vegetables"],
        "nutrients": {"protein": 0.79, "iron": 0.45, "calcium": 2.0, "fiber": 1.5, "vitamin_c": 6.5, "folate": 18.0, "zinc": 0.13, "magnesium": 32.0, "vitamin_a": 457.0, "potassium": 465.0},
    },
    {
        "name": "Buckwheat (cooked)",
        "aliases": ["kasha", "soba grain"],
        "tags": ["vegetarian", "gluten_free", "east_asian", "whole_grain"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170687",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 3.38, "iron": 0.80, "calcium": 7.0, "fiber": 2.7, "vitamin_c": 0.0, "folate": 14.0, "zinc": 0.61, "magnesium": 51.0},
    },
    {
        "name": "Amaranth (cooked)",
        "aliases": ["rajgira", "kiwicha"],
        "tags": ["vegetarian", "gluten_free", "whole_grain", "latin_american", "indian"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170683",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 3.8, "iron": 2.1, "calcium": 47.0, "fiber": 2.1, "vitamin_c": 0.0, "folate": 22.0, "zinc": 0.86, "magnesium": 65.0},
    },
    # ============================================================
    # LEGUMES & PULSES
    # ============================================================
    {
        "name": "Cowpeas / Black-eyed Peas (cooked)",
        "aliases": ["black-eyed peas", "lobiya", "niebe"],
        "tags": ["vegetarian", "west_african", "iron_rich", "high_protein", "high_fiber"],
        "cuisine_region": "west_african",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175198",
        "food_groups": ["legumes_pulses"],
        "nutrients": {"protein": 7.73, "iron": 2.51, "calcium": 24.0, "fiber": 6.5, "vitamin_c": 0.4, "folate": 208.0, "zinc": 1.29, "magnesium": 53.0},
    },
    {
        "name": "Pigeon Peas (cooked)",
        "aliases": ["toor dal raw", "arhar", "gungo peas"],
        "tags": ["vegetarian", "indian", "caribbean", "iron_rich", "high_protein"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:172437",
        "food_groups": ["legumes_pulses"],
        "nutrients": {"protein": 6.76, "iron": 1.11, "calcium": 43.0, "fiber": 6.7, "vitamin_c": 0.0, "folate": 111.0, "zinc": 0.90, "magnesium": 46.0},
    },
    {
        "name": "Kidney Beans (cooked)",
        "aliases": ["rajma", "red beans", "frijoles rojos"],
        "tags": ["vegetarian", "iron_rich", "high_protein", "high_fiber", "indian", "latin_american"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175194",
        "food_groups": ["legumes_pulses"],
        "nutrients": {"protein": 8.67, "iron": 2.94, "calcium": 28.0, "fiber": 7.4, "vitamin_c": 1.2, "folate": 130.0, "zinc": 1.07, "magnesium": 45.0},
    },
    {
        "name": "Fava Beans (cooked)",
        "aliases": ["broad beans", "ful medames base", "habas"],
        "tags": ["vegetarian", "middle_eastern", "iron_rich", "high_protein"],
        "cuisine_region": "middle_eastern",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175191",
        "food_groups": ["legumes_pulses"],
        "nutrients": {"protein": 7.6, "iron": 1.5, "calcium": 36.0, "fiber": 5.4, "vitamin_c": 0.3, "folate": 104.0, "zinc": 1.01, "magnesium": 43.0},
    },
    {
        "name": "Soybeans (cooked)",
        "aliases": ["edamame shelled", "soya beans"],
        "tags": ["vegetarian", "east_asian", "high_protein", "complete_protein"],
        "cuisine_region": "east_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:174270",
        "food_groups": ["legumes_pulses"],
        "nutrients": {"protein": 16.6, "iron": 5.14, "calcium": 102.0, "fiber": 6.0, "vitamin_c": 1.7, "folate": 54.0, "zinc": 1.15, "magnesium": 86.0},
    },
    {
        "name": "Pinto Beans (cooked)",
        "aliases": ["frijoles pintos"],
        "tags": ["vegetarian", "latin_american", "high_fiber", "high_protein"],
        "cuisine_region": "latin_american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175197",
        "food_groups": ["legumes_pulses"],
        "nutrients": {"protein": 9.01, "iron": 2.09, "calcium": 46.0, "fiber": 9.0, "vitamin_c": 0.8, "folate": 172.0, "zinc": 0.96, "magnesium": 50.0},
    },
    # ============================================================
    # VEGETABLES
    # ============================================================
    {
        "name": "Bok Choy (cooked)",
        "aliases": ["pak choi", "chinese cabbage"],
        "tags": ["vegetarian", "east_asian", "calcium_rich", "leafy_green"],
        "cuisine_region": "east_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169396",
        "food_groups": ["dark_leafy_greens", "calcium_sources"],
        "nutrients": {"protein": 1.56, "iron": 0.80, "calcium": 93.0, "fiber": 1.0, "vitamin_c": 26.0, "folate": 66.0, "zinc": 0.19, "magnesium": 11.0},
    },
    {
        "name": "Taro (cooked)",
        "aliases": ["arbi", "dasheen", "cocoyam"],
        "tags": ["vegetarian", "gluten_free", "west_african", "caribbean", "east_asian"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169985",
        "food_groups": ["whole_grains"],
        "nutrients": {"protein": 0.52, "iron": 0.72, "calcium": 18.0, "fiber": 3.7, "vitamin_c": 5.0, "folate": 19.0, "zinc": 0.27, "magnesium": 30.0},
    },
    {
        "name": "Okra (cooked)",
        "aliases": ["bhindi", "lady fingers", "gumbo"],
        "tags": ["vegetarian", "west_african", "indian", "high_fiber"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169260",
        "food_groups": ["cruciferous"],
        "nutrients": {"protein": 1.87, "iron": 0.28, "calcium": 77.0, "fiber": 2.5, "vitamin_c": 16.3, "folate": 46.0, "zinc": 0.43, "magnesium": 36.0},
    },
    {
        "name": "Bitter Melon (cooked)",
        "aliases": ["karela", "bitter gourd", "ampalaya"],
        "tags": ["vegetarian", "indian", "east_asian", "southeast_asian"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:168391",
        "food_groups": ["cruciferous"],
        "nutrients": {"protein": 0.84, "iron": 0.38, "calcium": 9.0, "fiber": 2.0, "vitamin_c": 33.0, "folate": 51.0, "zinc": 0.46, "magnesium": 16.0},
    },
    {
        "name": "Daikon Radish (raw)",
        "aliases": ["mooli", "white radish", "lo bok"],
        "tags": ["vegetarian", "east_asian", "indian"],
        "cuisine_region": "east_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169276",
        "food_groups": ["cruciferous"],
        "nutrients": {"protein": 0.6, "iron": 0.4, "calcium": 27.0, "fiber": 1.6, "vitamin_c": 22.0, "folate": 28.0, "zinc": 0.15, "magnesium": 16.0},
    },
    {
        "name": "Jicama (raw)",
        "aliases": ["yam bean", "mexican turnip"],
        "tags": ["vegetarian", "latin_american", "high_fiber"],
        "cuisine_region": "latin_american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170073",
        "food_groups": ["cruciferous"],
        "nutrients": {"protein": 0.72, "iron": 0.60, "calcium": 12.0, "fiber": 4.9, "vitamin_c": 20.2, "folate": 12.0, "zinc": 0.16, "magnesium": 12.0},
    },
    {
        "name": "Avocado",
        "aliases": ["aguacate", "palta"],
        "tags": ["vegetarian", "latin_american", "healthy_fat"],
        "cuisine_region": "latin_american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:171705",
        "food_groups": ["nuts_seeds"],
        "nutrients": {"protein": 2.0, "iron": 0.55, "calcium": 12.0, "fiber": 6.7, "vitamin_c": 10.0, "folate": 81.0, "zinc": 0.64, "magnesium": 29.0, "potassium": 485.0, "vitamin_e": 2.07},
    },
    # ============================================================
    # FRUITS
    # ============================================================
    {
        "name": "Mango",
        "aliases": ["aam", "mangue"],
        "tags": ["vegetarian", "indian", "southeast_asian", "latin_american", "vitamin_a_rich"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169910",
        "food_groups": ["citrus_berries"],
        "nutrients": {"protein": 0.82, "iron": 0.16, "calcium": 11.0, "fiber": 1.6, "vitamin_c": 36.4, "folate": 43.0, "zinc": 0.09, "magnesium": 10.0, "vitamin_a": 54.0},
    },
    {
        "name": "Papaya",
        "aliases": ["pawpaw"],
        "tags": ["vegetarian", "latin_american", "southeast_asian", "vitamin_c_rich"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169926",
        "food_groups": ["citrus_berries"],
        "nutrients": {"protein": 0.47, "iron": 0.25, "calcium": 20.0, "fiber": 1.7, "vitamin_c": 60.9, "folate": 37.0, "zinc": 0.08, "magnesium": 21.0, "vitamin_a": 47.0},
    },
    {
        "name": "Guava",
        "aliases": ["amrud", "guayaba"],
        "tags": ["vegetarian", "latin_american", "indian", "vitamin_c_rich"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169878",
        "food_groups": ["citrus_berries"],
        "nutrients": {"protein": 2.55, "iron": 0.26, "calcium": 18.0, "fiber": 5.4, "vitamin_c": 228.3, "folate": 49.0, "zinc": 0.23, "magnesium": 22.0},
    },
    {
        "name": "Pomegranate",
        "aliases": ["anar", "granada"],
        "tags": ["vegetarian", "middle_eastern", "indian", "antioxidant_rich"],
        "cuisine_region": "middle_eastern",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169134",
        "food_groups": ["citrus_berries"],
        "nutrients": {"protein": 1.67, "iron": 0.30, "calcium": 10.0, "fiber": 4.0, "vitamin_c": 10.2, "folate": 38.0, "zinc": 0.35, "magnesium": 12.0, "potassium": 236.0},
    },
    {
        "name": "Dates (deglet noor)",
        "aliases": ["khajoor", "tamr"],
        "tags": ["vegetarian", "middle_eastern", "indian", "high_fiber"],
        "cuisine_region": "middle_eastern",
        "source": "USDA FoodData Central",
        "source_id": "FDC:168191",
        "food_groups": ["citrus_berries"],
        "nutrients": {"protein": 2.45, "iron": 1.02, "calcium": 39.0, "fiber": 8.0, "vitamin_c": 0.4, "folate": 19.0, "zinc": 0.29, "magnesium": 43.0, "potassium": 656.0},
    },
    {
        "name": "Tamarind",
        "aliases": ["imli", "tamarin"],
        "tags": ["vegetarian", "indian", "southeast_asian", "west_african"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169941",
        "food_groups": ["citrus_berries"],
        "nutrients": {"protein": 2.8, "iron": 2.8, "calcium": 74.0, "fiber": 5.1, "vitamin_c": 3.5, "folate": 14.0, "zinc": 0.1, "magnesium": 92.0},
    },
    # ============================================================
    # PROTEINS
    # ============================================================
    {
        "name": "Lamb (cooked)",
        "aliases": ["mutton", "gosht"],
        "tags": ["non_vegetarian", "middle_eastern", "indian", "iron_rich", "high_protein"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:174373",
        "food_groups": ["iron_rich_proteins"],
        "nutrients": {"protein": 25.5, "iron": 1.88, "calcium": 16.0, "fiber": 0.0, "vitamin_c": 0.0, "folate": 18.0, "zinc": 4.46, "magnesium": 23.0, "b12": 2.31},
    },
    {
        "name": "Goat (cooked)",
        "aliases": ["chevon", "cabrito"],
        "tags": ["non_vegetarian", "west_african", "caribbean", "indian", "iron_rich"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175306",
        "food_groups": ["iron_rich_proteins"],
        "nutrients": {"protein": 27.1, "iron": 3.73, "calcium": 17.0, "fiber": 0.0, "vitamin_c": 0.0, "folate": 3.0, "zinc": 5.27, "magnesium": 25.0, "b12": 1.13},
    },
    {
        "name": "Shrimp (cooked)",
        "aliases": ["prawns", "jhinga", "camaron"],
        "tags": ["non_vegetarian", "east_asian", "southeast_asian", "latin_american", "high_protein"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175180",
        "food_groups": ["iron_rich_proteins", "omega3_sources"],
        "nutrients": {"protein": 20.91, "iron": 2.41, "calcium": 52.0, "fiber": 0.0, "vitamin_c": 0.0, "folate": 3.0, "zinc": 1.34, "magnesium": 34.0, "b12": 1.11, "omega_3_epa": 0.171, "omega_3_dha": 0.144},
    },
    {
        "name": "Mackerel (cooked)",
        "aliases": ["bangda", "caballa"],
        "tags": ["non_vegetarian", "omega_3_rich", "high_protein"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175121",
        "food_groups": ["omega3_sources", "iron_rich_proteins"],
        "nutrients": {"protein": 23.85, "iron": 1.57, "calcium": 15.0, "fiber": 0.0, "vitamin_c": 0.4, "folate": 1.0, "zinc": 0.63, "magnesium": 97.0, "omega_3_dha": 1.195, "omega_3_epa": 0.504, "vitamin_d": 16.1},
    },
    {
        "name": "Tilapia (cooked)",
        "aliases": ["st peter's fish"],
        "tags": ["non_vegetarian", "west_african", "high_protein", "lean"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175185",
        "food_groups": ["iron_rich_proteins"],
        "nutrients": {"protein": 26.15, "iron": 0.69, "calcium": 14.0, "fiber": 0.0, "vitamin_c": 0.0, "folate": 6.0, "zinc": 0.43, "magnesium": 34.0, "b12": 1.86},
    },
    # ============================================================
    # NUTS, SEEDS & OILS
    # ============================================================
    {
        "name": "Peanuts (roasted)",
        "aliases": ["groundnuts", "moongphali", "cacahuate"],
        "tags": ["vegetarian", "west_african", "indian", "high_protein"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:172430",
        "food_groups": ["nuts_seeds", "legumes_pulses"],
        "nutrients": {"protein": 24.35, "iron": 2.26, "calcium": 54.0, "fiber": 8.0, "vitamin_c": 0.0, "folate": 145.0, "zinc": 3.31, "magnesium": 176.0, "vitamin_e": 6.93},
    },
    {
        "name": "Sesame Seeds",
        "aliases": ["til", "tahini base", "ajonjoli"],
        "tags": ["vegetarian", "middle_eastern", "indian", "east_asian", "calcium_rich", "iron_rich"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170150",
        "food_groups": ["nuts_seeds", "calcium_sources"],
        "nutrients": {"protein": 17.73, "iron": 14.55, "calcium": 975.0, "fiber": 11.8, "vitamin_c": 0.0, "folate": 97.0, "zinc": 7.75, "magnesium": 351.0},
    },
    {
        "name": "Pumpkin Seeds",
        "aliases": ["pepitas"],
        "tags": ["vegetarian", "latin_american", "magnesium_rich", "zinc_rich"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170556",
        "food_groups": ["nuts_seeds"],
        "nutrients": {"protein": 30.23, "iron": 8.82, "calcium": 46.0, "fiber": 6.0, "vitamin_c": 1.9, "folate": 58.0, "zinc": 7.81, "magnesium": 592.0},
    },
    {
        "name": "Chia Seeds",
        "aliases": ["chia"],
        "tags": ["vegetarian", "latin_american", "omega_3_rich", "high_fiber"],
        "cuisine_region": "latin_american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170554",
        "food_groups": ["nuts_seeds", "omega3_sources"],
        "nutrients": {"protein": 16.54, "iron": 7.72, "calcium": 631.0, "fiber": 34.4, "vitamin_c": 1.6, "folate": 49.0, "zinc": 4.58, "magnesium": 335.0, "omega_3_ala": 17.83},
    },
    {
        "name": "Cashews (raw)",
        "aliases": ["kaju"],
        "tags": ["vegetarian", "indian", "west_african", "magnesium_rich"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170162",
        "food_groups": ["nuts_seeds"],
        "nutrients": {"protein": 18.22, "iron": 6.68, "calcium": 37.0, "fiber": 3.3, "vitamin_c": 0.5, "folate": 25.0, "zinc": 5.78, "magnesium": 292.0},
    },
    # ============================================================
    # FERMENTED & DAIRY
    # ============================================================
    {
        "name": "Miso",
        "aliases": ["miso paste"],
        "tags": ["vegetarian", "east_asian", "fermented", "probiotic"],
        "cuisine_region": "east_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:172442",
        "food_groups": ["fermented_foods"],
        "nutrients": {"protein": 12.79, "iron": 2.49, "calcium": 57.0, "fiber": 5.4, "vitamin_c": 0.0, "folate": 19.0, "zinc": 2.56, "magnesium": 48.0},
    },
    {
        "name": "Tempeh",
        "aliases": ["fermented soybean cake"],
        "tags": ["vegetarian", "vegan", "southeast_asian", "fermented", "high_protein", "complete_protein"],
        "cuisine_region": "southeast_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:174272",
        "food_groups": ["fermented_foods", "legumes_pulses"],
        "nutrients": {"protein": 18.54, "iron": 2.73, "calcium": 111.0, "fiber": 0.0, "vitamin_c": 0.0, "folate": 24.0, "zinc": 1.14, "magnesium": 81.0, "b12": 0.08},
    },
    {
        "name": "Kefir (plain)",
        "aliases": ["fermented milk"],
        "tags": ["vegetarian", "middle_eastern", "fermented", "probiotic", "calcium_rich"],
        "cuisine_region": "middle_eastern",
        "source": "USDA FoodData Central",
        "source_id": "FDC:172186",
        "food_groups": ["fermented_foods", "calcium_sources"],
        "nutrients": {"protein": 3.79, "iron": 0.04, "calcium": 130.0, "fiber": 0.0, "vitamin_c": 0.2, "folate": 13.0, "zinc": 0.46, "magnesium": 12.0, "b12": 0.29},
    },
    {
        "name": "Paneer",
        "aliases": ["Indian cottage cheese"],
        "tags": ["vegetarian", "indian", "calcium_rich", "high_protein"],
        "cuisine_region": "indian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:173418",
        "food_groups": ["calcium_sources"],
        "nutrients": {"protein": 11.12, "iron": 0.44, "calcium": 208.0, "fiber": 0.0, "vitamin_c": 0.0, "folate": 37.0, "zinc": 0.66, "magnesium": 8.0, "b12": 0.83},
    },
    {
        "name": "Ghee",
        "aliases": ["clarified butter"],
        "tags": ["vegetarian", "indian", "middle_eastern"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:171315",
        "food_groups": ["calcium_sources"],
        "nutrients": {"protein": 0.28, "iron": 0.0, "calcium": 4.0, "fiber": 0.0, "vitamin_c": 0.0, "folate": 0.0, "zinc": 0.0, "magnesium": 0.0, "vitamin_a": 824.0, "vitamin_e": 2.80},
    },
    # ============================================================
    # HERBS, SPICES & AROMATICS
    # ============================================================
    {
        "name": "Cinnamon (ground)",
        "aliases": ["dalchini", "canela"],
        "tags": ["vegetarian", "spice", "anti_inflammatory", "global"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:171320",
        "food_groups": ["herbs_spices"],
        "nutrients": {"protein": 3.99, "iron": 8.32, "calcium": 1002.0, "fiber": 53.1, "vitamin_c": 3.8, "folate": 6.0, "zinc": 1.83, "magnesium": 60.0},
    },
    {
        "name": "Cumin Seeds",
        "aliases": ["jeera", "comino"],
        "tags": ["vegetarian", "spice", "indian", "middle_eastern", "latin_american"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170923",
        "food_groups": ["herbs_spices"],
        "nutrients": {"protein": 17.81, "iron": 66.36, "calcium": 931.0, "fiber": 10.5, "vitamin_c": 7.7, "folate": 10.0, "zinc": 4.80, "magnesium": 366.0},
    },
    {
        "name": "Coriander / Cilantro (fresh)",
        "aliases": ["dhania", "cilantro", "chinese parsley"],
        "tags": ["vegetarian", "herb", "indian", "latin_american", "east_asian"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169997",
        "food_groups": ["herbs_spices"],
        "nutrients": {"protein": 2.13, "iron": 1.77, "calcium": 67.0, "fiber": 2.8, "vitamin_c": 27.0, "folate": 62.0, "zinc": 0.50, "magnesium": 26.0, "vitamin_a": 337.0},
    },
    {
        "name": "Lemongrass",
        "aliases": ["citronella", "sera"],
        "tags": ["vegetarian", "southeast_asian", "herb"],
        "cuisine_region": "southeast_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:168573",
        "food_groups": ["herbs_spices"],
        "nutrients": {"protein": 1.82, "iron": 8.17, "calcium": 65.0, "fiber": 0.0, "vitamin_c": 2.6, "folate": 75.0, "zinc": 2.23, "magnesium": 60.0},
    },
    {
        "name": "Coconut Milk (canned)",
        "aliases": ["nariyal doodh", "santan"],
        "tags": ["vegetarian", "vegan", "southeast_asian", "indian", "caribbean"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170172",
        "food_groups": ["nuts_seeds"],
        "nutrients": {"protein": 2.29, "iron": 3.30, "calcium": 18.0, "fiber": 2.2, "vitamin_c": 2.8, "folate": 16.0, "zinc": 0.67, "magnesium": 46.0},
    },
]
