"""
Curated US food seed data.
Source: USDA FoodData Central (fdc.nal.usda.gov).
Each entry includes FDC ID for transparency tap-through.
"""

US_FOODS = [
    # === Dark Leafy Greens ===
    {
        "name": "Spinach (raw)",
        "aliases": ["baby spinach", "spinach leaves"],
        "tags": ["vegetarian", "american", "iron_rich", "leafy_green"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:168462",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/168462",
        "food_groups": ["dark_leafy_greens"],
        "nutrients": {
            "protein": 2.86, "iron": 2.71, "calcium": 99.0, "fiber": 2.2,
            "vitamin_c": 28.1, "folate": 194.0, "zinc": 0.53, "magnesium": 79.0,
            "vitamin_k": 482.9, "vitamin_a": 469.0, "potassium": 558.0,
        },
    },
    {
        "name": "Kale (raw)",
        "aliases": ["curly kale", "kale leaves"],
        "tags": ["vegetarian", "american", "iron_rich", "leafy_green", "cruciferous"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:168421",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/168421",
        "food_groups": ["dark_leafy_greens", "cruciferous"],
        "nutrients": {
            "protein": 4.28, "iron": 1.47, "calcium": 150.0, "fiber": 3.6,
            "vitamin_c": 120.0, "folate": 141.0, "zinc": 0.56, "magnesium": 47.0,
            "vitamin_k": 817.0, "vitamin_a": 500.0, "potassium": 491.0,
        },
    },
    # === Orange/Red Vegetables ===
    {
        "name": "Sweet Potato (baked)",
        "aliases": ["yam", "baked sweet potato"],
        "tags": ["vegetarian", "american", "vitamin_a_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:168482",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/168482",
        "food_groups": ["orange_red_vegetables"],
        "nutrients": {
            "protein": 2.01, "iron": 0.69, "calcium": 38.0, "fiber": 3.8,
            "vitamin_c": 19.6, "folate": 6.0, "zinc": 0.32, "magnesium": 27.0,
            "vitamin_a": 961.0, "potassium": 475.0,
        },
    },
    {
        "name": "Carrots (raw)",
        "aliases": ["carrot", "baby carrots"],
        "tags": ["vegetarian", "american", "vitamin_a_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170393",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170393",
        "food_groups": ["orange_red_vegetables"],
        "nutrients": {
            "protein": 0.93, "iron": 0.30, "calcium": 33.0, "fiber": 2.8,
            "vitamin_c": 5.9, "folate": 19.0, "zinc": 0.24, "magnesium": 12.0,
            "vitamin_a": 835.0, "potassium": 320.0,
        },
    },
    # === Cruciferous ===
    {
        "name": "Broccoli (cooked)",
        "aliases": ["steamed broccoli", "broccoli florets"],
        "tags": ["vegetarian", "american", "cruciferous", "vitamin_c_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170379",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170379",
        "food_groups": ["cruciferous"],
        "nutrients": {
            "protein": 2.38, "iron": 0.67, "calcium": 40.0, "fiber": 3.3,
            "vitamin_c": 64.9, "folate": 108.0, "zinc": 0.45, "magnesium": 21.0,
        },
    },
    # === Legumes & Pulses ===
    {
        "name": "Lentils (cooked)",
        "aliases": ["brown lentils", "green lentils", "red lentils"],
        "tags": ["vegetarian", "american", "iron_rich", "high_protein", "high_fiber"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:172421",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/172421",
        "food_groups": ["legumes_pulses"],
        "nutrients": {
            "protein": 9.02, "iron": 3.33, "calcium": 19.0, "fiber": 7.9,
            "vitamin_c": 1.5, "folate": 181.0, "zinc": 1.27, "magnesium": 36.0,
            "potassium": 369.0,
        },
    },
    {
        "name": "Black Beans (cooked)",
        "aliases": ["frijoles negros", "black turtle beans"],
        "tags": ["vegetarian", "american", "iron_rich", "high_protein", "high_fiber"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:173735",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/173735",
        "food_groups": ["legumes_pulses"],
        "nutrients": {
            "protein": 8.86, "iron": 2.10, "calcium": 27.0, "fiber": 8.7,
            "vitamin_c": 0.0, "folate": 149.0, "zinc": 1.12, "magnesium": 70.0,
        },
    },
    {
        "name": "Chickpeas (cooked)",
        "aliases": ["garbanzo beans", "chana"],
        "tags": ["vegetarian", "american", "iron_rich", "high_protein", "high_fiber"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:173757",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/173757",
        "food_groups": ["legumes_pulses"],
        "nutrients": {
            "protein": 8.86, "iron": 2.89, "calcium": 49.0, "fiber": 7.6,
            "vitamin_c": 1.3, "folate": 172.0, "zinc": 1.53, "magnesium": 48.0,
        },
    },
    # === Whole Grains ===
    {
        "name": "Brown Rice (cooked)",
        "aliases": ["whole grain rice"],
        "tags": ["vegetarian", "american", "whole_grain"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169704",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/169704",
        "food_groups": ["whole_grains"],
        "nutrients": {
            "protein": 2.32, "iron": 0.56, "calcium": 3.0, "fiber": 1.8,
            "vitamin_c": 0.0, "folate": 4.0, "zinc": 0.62, "magnesium": 39.0,
        },
    },
    {
        "name": "Oatmeal (cooked)",
        "aliases": ["oats", "porridge", "rolled oats"],
        "tags": ["vegetarian", "american", "whole_grain", "high_fiber"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:173904",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/173904",
        "food_groups": ["whole_grains"],
        "nutrients": {
            "protein": 2.37, "iron": 0.92, "calcium": 9.0, "fiber": 1.7,
            "vitamin_c": 0.0, "folate": 6.0, "zinc": 0.64, "magnesium": 27.0,
        },
    },
    {
        "name": "Quinoa (cooked)",
        "aliases": ["keen-wah"],
        "tags": ["vegetarian", "american", "whole_grain", "gluten_free", "complete_protein"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:168917",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/168917",
        "food_groups": ["whole_grains"],
        "nutrients": {
            "protein": 4.40, "iron": 1.49, "calcium": 17.0, "fiber": 2.8,
            "vitamin_c": 0.0, "folate": 42.0, "zinc": 1.09, "magnesium": 64.0,
        },
    },
    # === Nuts & Seeds ===
    {
        "name": "Almonds",
        "aliases": ["raw almonds", "almond"],
        "tags": ["vegetarian", "american", "vitamin_e_rich", "magnesium_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170567",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170567",
        "food_groups": ["nuts_seeds"],
        "nutrients": {
            "protein": 21.15, "iron": 3.71, "calcium": 269.0, "fiber": 12.5,
            "vitamin_c": 0.0, "folate": 44.0, "zinc": 3.12, "magnesium": 270.0,
            "vitamin_e": 25.63,
        },
    },
    {
        "name": "Walnuts",
        "aliases": ["akhrot"],
        "tags": ["vegetarian", "american", "omega_3_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170187",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170187",
        "food_groups": ["nuts_seeds", "omega3_sources"],
        "nutrients": {
            "protein": 15.23, "iron": 2.91, "calcium": 98.0, "fiber": 6.7,
            "vitamin_c": 1.3, "folate": 98.0, "zinc": 3.09, "magnesium": 158.0,
            "omega_3_ala": 9.08,
        },
    },
    {
        "name": "Flaxseeds",
        "aliases": ["linseed", "alsi"],
        "tags": ["vegetarian", "american", "omega_3_rich", "high_fiber"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169414",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/169414",
        "food_groups": ["nuts_seeds", "omega3_sources"],
        "nutrients": {
            "protein": 18.29, "iron": 5.73, "calcium": 255.0, "fiber": 27.3,
            "vitamin_c": 0.6, "folate": 87.0, "zinc": 4.34, "magnesium": 392.0,
            "omega_3_ala": 22.8,
        },
    },
    # === Omega-3 Sources ===
    {
        "name": "Salmon (cooked)",
        "aliases": ["atlantic salmon", "wild salmon"],
        "tags": ["non_vegetarian", "american", "omega_3_rich", "high_protein"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175168",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/175168",
        "food_groups": ["omega3_sources", "iron_rich_proteins"],
        "nutrients": {
            "protein": 25.44, "iron": 0.34, "calcium": 9.0, "fiber": 0.0,
            "vitamin_c": 0.0, "folate": 29.0, "zinc": 0.64, "magnesium": 37.0,
            "omega_3_dha": 1.429, "omega_3_epa": 0.411, "vitamin_d": 11.1,
        },
    },
    {
        "name": "Sardines (canned)",
        "aliases": ["tinned sardines"],
        "tags": ["non_vegetarian", "american", "omega_3_rich", "calcium_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:175139",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/175139",
        "food_groups": ["omega3_sources", "calcium_sources"],
        "nutrients": {
            "protein": 24.62, "iron": 2.92, "calcium": 382.0, "fiber": 0.0,
            "vitamin_c": 0.0, "folate": 10.0, "zinc": 1.31, "magnesium": 39.0,
            "omega_3_dha": 0.509, "omega_3_epa": 0.473, "vitamin_d": 4.8,
        },
    },
    # === Fermented Foods ===
    {
        "name": "Greek Yogurt (plain)",
        "aliases": ["yogurt", "plain yogurt"],
        "tags": ["vegetarian", "american", "fermented", "calcium_rich", "high_protein"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170903",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170903",
        "food_groups": ["fermented_foods", "calcium_sources"],
        "nutrients": {
            "protein": 10.19, "iron": 0.07, "calcium": 110.0, "fiber": 0.0,
            "vitamin_c": 0.0, "folate": 7.0, "zinc": 0.52, "magnesium": 11.0,
            "b12": 0.75,
        },
    },
    {
        "name": "Kimchi",
        "aliases": ["kimchee"],
        "tags": ["vegetarian", "korean", "fermented", "probiotic"],
        "cuisine_region": "east_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:174276",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/174276",
        "food_groups": ["fermented_foods", "cruciferous"],
        "nutrients": {
            "protein": 1.1, "iron": 0.5, "calcium": 33.0, "fiber": 1.6,
            "vitamin_c": 0.0, "folate": 52.0, "zinc": 0.22, "magnesium": 14.0,
        },
    },
    # === Iron-Rich Proteins ===
    {
        "name": "Chicken Breast (cooked)",
        "aliases": ["grilled chicken", "chicken"],
        "tags": ["non_vegetarian", "american", "high_protein", "lean"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:171077",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/171077",
        "food_groups": ["iron_rich_proteins"],
        "nutrients": {
            "protein": 31.02, "iron": 1.04, "calcium": 15.0, "fiber": 0.0,
            "vitamin_c": 0.0, "folate": 4.0, "zinc": 1.0, "magnesium": 29.0,
            "b12": 0.34,
        },
    },
    {
        "name": "Eggs (boiled)",
        "aliases": ["hard boiled egg", "egg"],
        "tags": ["vegetarian", "american", "high_protein", "b12_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:173424",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/173424",
        "food_groups": ["iron_rich_proteins"],
        "nutrients": {
            "protein": 12.58, "iron": 1.19, "calcium": 50.0, "fiber": 0.0,
            "vitamin_c": 0.0, "folate": 44.0, "zinc": 1.05, "magnesium": 10.0,
            "b12": 1.11, "vitamin_d": 2.2,
        },
    },
    # === Herbs & Spices ===
    {
        "name": "Turmeric (ground)",
        "aliases": ["haldi"],
        "tags": ["vegetarian", "spice", "anti_inflammatory"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:172231",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/172231",
        "food_groups": ["herbs_spices"],
        "nutrients": {
            "protein": 7.83, "iron": 41.42, "calcium": 183.0, "fiber": 21.1,
            "vitamin_c": 25.9, "folate": 39.0, "zinc": 4.35, "magnesium": 193.0,
        },
    },
    {
        "name": "Ginger (raw)",
        "aliases": ["adrak", "fresh ginger"],
        "tags": ["vegetarian", "spice", "anti_inflammatory"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169231",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/169231",
        "food_groups": ["herbs_spices"],
        "nutrients": {
            "protein": 1.82, "iron": 0.60, "calcium": 16.0, "fiber": 2.0,
            "vitamin_c": 5.0, "folate": 11.0, "zinc": 0.34, "magnesium": 43.0,
        },
    },
    # === Citrus & Berries ===
    {
        "name": "Blueberries",
        "aliases": ["fresh blueberries"],
        "tags": ["vegetarian", "american", "antioxidant_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:171711",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/171711",
        "food_groups": ["citrus_berries"],
        "nutrients": {
            "protein": 0.74, "iron": 0.28, "calcium": 6.0, "fiber": 2.4,
            "vitamin_c": 9.7, "folate": 6.0, "zinc": 0.16, "magnesium": 6.0,
            "vitamin_k": 19.3,
        },
    },
    {
        "name": "Orange",
        "aliases": ["navel orange", "fresh orange"],
        "tags": ["vegetarian", "american", "vitamin_c_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169097",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/169097",
        "food_groups": ["citrus_berries"],
        "nutrients": {
            "protein": 0.94, "iron": 0.10, "calcium": 40.0, "fiber": 2.4,
            "vitamin_c": 53.2, "folate": 30.0, "zinc": 0.07, "magnesium": 10.0,
        },
    },
    # === Alliums ===
    {
        "name": "Garlic (raw)",
        "aliases": ["lehsun", "fresh garlic"],
        "tags": ["vegetarian", "global", "prebiotic"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:169230",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/169230",
        "food_groups": ["alliums"],
        "nutrients": {
            "protein": 6.36, "iron": 1.70, "calcium": 181.0, "fiber": 2.1,
            "vitamin_c": 31.2, "folate": 3.0, "zinc": 1.16, "magnesium": 25.0,
        },
    },
    {
        "name": "Onion (raw)",
        "aliases": ["pyaz", "fresh onion"],
        "tags": ["vegetarian", "global", "prebiotic"],
        "cuisine_region": "global",
        "source": "USDA FoodData Central",
        "source_id": "FDC:170000",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170000",
        "food_groups": ["alliums"],
        "nutrients": {
            "protein": 1.10, "iron": 0.21, "calcium": 23.0, "fiber": 1.7,
            "vitamin_c": 7.4, "folate": 19.0, "zinc": 0.17, "magnesium": 10.0,
        },
    },
    # === Calcium Sources ===
    {
        "name": "Whole Milk",
        "aliases": ["cow's milk", "milk"],
        "tags": ["vegetarian", "american", "calcium_rich"],
        "cuisine_region": "american",
        "source": "USDA FoodData Central",
        "source_id": "FDC:171265",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/171265",
        "food_groups": ["calcium_sources"],
        "nutrients": {
            "protein": 3.15, "iron": 0.03, "calcium": 113.0, "fiber": 0.0,
            "vitamin_c": 0.0, "folate": 5.0, "zinc": 0.37, "magnesium": 10.0,
            "vitamin_d": 1.3, "b12": 0.45,
        },
    },
    {
        "name": "Tofu (firm)",
        "aliases": ["bean curd"],
        "tags": ["vegetarian", "vegan", "calcium_rich", "high_protein"],
        "cuisine_region": "east_asian",
        "source": "USDA FoodData Central",
        "source_id": "FDC:174272",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/174272",
        "food_groups": ["calcium_sources", "legumes_pulses"],
        "nutrients": {
            "protein": 8.19, "iron": 5.36, "calcium": 350.0, "fiber": 0.3,
            "vitamin_c": 0.1, "folate": 15.0, "zinc": 0.80, "magnesium": 30.0,
        },
    },
]
